name: base
channels:
  - conda-forge
  - nodefaults
dependencies:
  - numpy
  - arm_pyart
  - dask
  - cartopy
  - cmcrameri
  - ca-certificates
  - certifi
  - openssl
  - ipdb
  - pandas
  - h5py
  - matplotlib
